### ISSUE TITLE
Request: Settings | File Name Format

### ISSUE THREAD

**Issue by CodingFan72** [thomaskoppelaar/vscode-repeating-notes#2]
Hi Thomas,

I like your extension.

I have one "small" request: 

Would it be possible, that the user can modifiy the file name formats in the settings?

Some formats are better for sorting than the others.

For Example:

```
2021-01-11.md
2021-01-12.md
```

instead of 

```
11-01-2021.md   // Current version
12-01-2021.md
```

or

```
2021-01-january.md
2021-02-febuary.md
2022-01-january.md
```

instead of

```
febuary-2021.md
january-2021.md   // Current version
january-2022.md
```

or

```
2021-week-3.md
```

instead of

```
week-3-2021.md   // Current version
```

**Comment by thomaskoppelaar** [comment]
Hi @CodingFan72 ,

It's been a while since I've worked on this project, but I'm glad you like it :sweat_smile: 

I'll try my best at implementing this feature this week - If I end up archiving this, I'll look around for a substitute extension that you might be interested in.
